// old-svelte-frontend/src/routes/courses/+page.svelte
<script lang="ts">
	import Container from '$lib/components/ui/container.svelte';
	import Banner from '$lib/components/ui/banner.svelte';
	import Breadcrumbs from '$lib/components/ui/breadcrumbs.svelte';

	const crumbs = [
		{
			title: 'Home',
			url: '/'
		},
		{
			title: 'Courses',
			url: '/courses'
		}
	];
</script>

<div class="flex flex-col flex-1">
	<Banner>Courses</Banner>
	<Breadcrumbs breadcrumbs={crumbs} />
	<div class="bg-pink-100 py-10 flex-1">
		<Container>
			<div class="flex flex-col sm:flex-row items-center justify-around py-10">
				<a class="mb-6 block" href="/courses/mini-bijou">
					<img src="/level-1-300x300.png" alt="Mini Bijou" />
					<span>Mini Bijou</span>
				</a>
				<a class="mb-6 block" href="/courses/petit-bijou">
					<img src="/level-2-300x300.png" alt="Petit Bijou" />
					<span>Petit Bijou</span>
				</a>
				<!-- <a class="mb-6 block" href="/courses/top-bijou">
					<img src="/level-3-300x300.png" alt="Top Bijou" />
					<span>Top Bijou</span>
				</a> -->
			</div>
		</Container>
	</div>
</div>

<style>
	a img {
		max-width: 140px;
		margin-bottom: 20px;
		display: block;
	}

	a {
		text-align: center;
		font-size: 24px;
		display: block;
	}
	a span {
		font-weight: bold;
	}
</style>

// resources/js/pages/courses.tsx
import { type SharedData } from '@/types';
import { Head, Link, usePage } from '@inertiajs/react';
import Footer from '@/components/footer';
import Header from '@/components/header';
import miniBijou from '@/images/mini-bijou.png';
import petitBijou from '@/images/petit-bijou.png';

export default function Courses() {
    const { auth } = usePage<SharedData>().props;

  return (
    <div className="flex flex-col min-h-screen" style={{ backgroundColor: "#FEF4F3" }}>
      <Header name="Courses" />

      <div className="flex flex-1 flex-col sm:flex-row items-center justify-around py-10">
        <div>
          <Link href="courses/minibijou" ><img width="150" height="150" alt="Mini-Bijou" src={miniBijou}></img></Link>
          <span className='flex justify-center text-bold text-3xl pt-5'>Mini Bijou</span>
        </div>
        <div>
          <Link href="courses/petitbijou"><img width="150" height="150" alt="Petit-Bijou" src={petitBijou}></img></Link>
          <span className='flex justify-center text-bold text-3xl pt-5'>Petit Bijou</span>
        </div>
      </div>

      <Footer />
    </div>
  )
}
